name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  schedule:
    # Run monthly on the 1st at 00:00 UTC
    - cron: "0 0 1 * *"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        node-version: [18, 20, 22]
        docker-variant: [cli, dind, dind-rootless]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=node${{ matrix.node-version }}-${{ matrix.docker-variant }}
            type=raw,value=latest,enable=${{ matrix.node-version == '20' && matrix.docker-variant == 'dind' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NODE_VERSION=${{ matrix.node-version }}
            DOCKER_VARIANT=${{ matrix.docker-variant }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
